/**
 * Consolidated copyright and source disclosures for Settings (in-app, not legal advice).
 * Update when counsel approves final wording — see docs/LICENSING_SCRIPTURE.md.
 */

export const COPYRIGHT_MODAL_SECTIONS: { title: string; paragraphs: string[] }[] = [
  {
    title: "Scripture",
    paragraphs: [
      "When BibleByte displays the New International Version (NIV), text is used under applicable licenses. The NIV is copyright © 1973, 1978, 1984, 2011 by Biblica, Inc.® Used by permission of Biblica, Inc. All rights reserved worldwide.",
      "Scripture may be delivered via API.Bible and related services; use of that content is subject to API.Bible’s terms and to your organization’s agreements for the translation edition in use.",
      "Some screens still show placeholder or summary text where licensed verse wording is not yet enabled—that material is not a substitute for a licensed Bible text.",
    ],
  },
  {
    title: "BibleByte AI companion",
    paragraphs: [
      "Replies are generated by an AI model (e.g. OpenAI) using prompts designed for respectful, scripture-aware conversation. They are not divine guidance, not a substitute for pastors or licensed professionals, and may be incomplete or incorrect—always compare with Scripture and trusted teaching.",
    ],
  },
  {
    title: "Daily cues & snippets",
    paragraphs: [
      "Daily verse rows and widget-oriented payloads may use placeholder fields until publisher workflows mark content as licensed for each surface. Attribution notes in the app flag placeholder modes where applicable.",
    ],
  },
];
